{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "## 1. Understanding Arrow Functions & Lexical this\n",
        "Consider the following code and predict the output. Explain why the behavior occurs.\n",
        "```\n",
        "const person = {\n",
        "  name: \"Alice\",\n",
        "  greet: function () {\n",
        "    setTimeout(() => {\n",
        "      console.log(`Hello, my name is ${this.name}`);\n",
        "    }, 1000);\n",
        "  },\n",
        "};\n",
        "\n",
        "person.greet();\n",
        "```\n",
        "\n",
        "-\n",
        "  * Output: Prints \"Hello, my name is Alice\" to console after 1 second.\n",
        "  * Explanation: This code calls greet function inside person object, which have a timer of 1 second after that it gets name Alice from the caller object, where in this case is person. Then prints \"Hello, my name is Alice\" to the console.\n",
        "\n",
        "## 2.  Convert Traditional Functions to Arrow Functions\n",
        "Rewrite the following function using arrow functions without changing the behavior:\n",
        "\n",
        "Original Code:\n",
        "```\n",
        "function multiply(a, b) {\n",
        "  return a * b;\n",
        "}\n",
        "const obj = {\n",
        "  value: 10,\n",
        "  add: function (num) {\n",
        "    return this.value + num;\n",
        "  },\n",
        "};\n",
        "\n",
        "console.log(multiply(5, 3));\n",
        "console.log(obj.add(5));\n",
        "```\n",
        "\n",
        "Arrow function code:\n",
        "```\n",
        "const multiply = (a, b) => a * b;\n",
        "\n",
        "const obj = {\n",
        "  value: 10,\n",
        "  add: (obj, num) => {\n",
        "    return obj.value + num;\n",
        "  },\n",
        "};\n",
        "\n",
        "console.log(multiply(5, 3));\n",
        "console.log(obj.add(obj, 5));\n",
        "```\n",
        "Explanation: Appling arrow function is not possible in add function of obj, because it uses this keyword which is not available in arrow functions, but it can be possible if be pass the same object as an argument.\n",
        "\n",
        "##3. Handling Errors in Async-Await (Try-Catch Required)\n",
        "Modify the following function to use async-await and proper error handling (try-catch).\n",
        "\n",
        "* Original Code (With Promise):\n",
        "  ```\n",
        "  function fetchData() {\n",
        "    return new Promise((resolve, reject) => {\n",
        "      setTimeout(() => {\n",
        "        let success = Math.random() > 0.5;\n",
        "        success ? resolve(\"Data received\") : reject(\"Error fetching data\");\n",
        "      }, 2000);\n",
        "    });s\n",
        "  }\n",
        "\n",
        "  fetchData().then(console.log).catch(console.error);\n",
        "  ```\n",
        "\n",
        "- New code with try-catch and async-await\n",
        "  ```\n",
        "  function fetchData() {\n",
        "    return new Promise((resolve, reject) => {\n",
        "      setTimeout(() => {\n",
        "        let success = Math.random() > 0.5;\n",
        "        success ? resolve(\"Data received\") : reject(\"Error fetching data\");\n",
        "      }, 2000);\n",
        "    });\n",
        "  }\n",
        "\n",
        "  (async function getData() {\n",
        "    try {\n",
        "      const result = await fetchData();\n",
        "      console.log(result);\n",
        "    } catch (error) {\n",
        "      console.error(error);\n",
        "    }\n",
        "  })();\n",
        "  ```\n",
        "\n",
        "## 4. Async Function with Multiple Await Calls\n",
        "Write an async function that\n",
        "  * Fetches user data after 1 second\n",
        "  * Fetches order details after 2 seconds\n",
        "  * Fetches payment status after 3 seconds\n",
        "  * Logs the final \"Order completed\" message\n",
        "  * Use await to ensure each step executes sequentially.\n",
        "- Code for given task:\n",
        "\n",
        "  ```\n",
        "  const getUserData = (name) =>\n",
        "    new Promise((resolve) => {\n",
        "      setTimeout(() => {\n",
        "        resolve(`User Data for ${name} Received!`);\n",
        "      }, 1000);\n",
        "    });\n",
        "\n",
        "  const getOrderDetails = (name) =>\n",
        "    new Promise((resolve) => {\n",
        "      setTimeout(() => {\n",
        "        resolve(`Order details for ${name} Received!`);\n",
        "      }, 1000);\n",
        "    });\n",
        "\n",
        "  const getPaymentStatus = (name) =>\n",
        "    new Promise((resolve) => {\n",
        "      setTimeout(() => {\n",
        "        resolve(`Payment status for ${name} Received!`);\n",
        "      }, 1000);\n",
        "    });\n",
        "\n",
        "  async function completePurchase(userName) {\n",
        "    try {\n",
        "      const userData = await getUserData(userName);\n",
        "      console.log(userData);\n",
        "\n",
        "      const orderDetails = await getOrderDetails(userName);\n",
        "      console.log(orderDetails);\n",
        "\n",
        "      const paymentStatus = await getPaymentStatus(userName);\n",
        "      console.log(paymentStatus);\n",
        "\n",
        "      console.log(\"Order Completed\");\n",
        "    } catch (error) {\n",
        "      console.log(\"Order failed: \", error);\n",
        "    }\n",
        "  }\n",
        "\n",
        "  completePurchase(\"Manish\");\n",
        "  ```\n",
        "\n",
        "## 5. Handling Synchronous Errors with try-catch\n",
        "Write a function that\n",
        "  * Accepts a string input\n",
        "  * Converts it to a number and returns its square\n",
        "  * Uses try-catch to handle cases where the input is not a valid number\n",
        "  * If the error occurs, return \"Invalid Input\" instead of crashing.\n",
        "- Javascript code for given task:\n",
        "\n",
        "  ```\n",
        "  const getSquare = (inputInString) => {\n",
        "    try {\n",
        "      const numValue = Number(inputInString);\n",
        "      if (isNaN(numValue)) throw new Error(\"Invalid number input\");\n",
        "\n",
        "      const result = numValue * numValue;\n",
        "      return String(result);\n",
        "    } catch (error) {\n",
        "      return \"Invalid Input\";\n",
        "    }\n",
        "  };\n",
        "\n",
        "  console.log(getSquare(\"4\"));\n",
        "  console.log(getSquare(\"8d\"));\n",
        "  console.log(getSquare(\"8\"));\n",
        "  ```"
      ],
      "metadata": {
        "id": "1Ji_UHuAg_kn"
      }
    }
  ]
}